#!/bin/bash
# Copyright 2016, Rackspace US, Inc.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#
# (c) 2016, Kevin Carter <kevin.carter@rackspace.com>

if [ ${DIB_DEBUG_TRACE:-0} -gt 0 ]; then
    set -x
else
    set -v
fi

set -eu
set -o pipefail

OSA_RELEASE=${OSA_RELEASE:-master}
OSA_DEV_MODE=${OSA_DEV_MODE:-true}
OSA_CONSTRAINTS=${OSA_CONSTRAINTS:-https://raw.githubusercontent.com/openstack/requirements/master/upper-constraints.txt}
ELEMENT_DIR=$(pwd)

function ansible_tag_filter {
  TAGS=$($1 --list-tags | grep -o '\s\[.*\]' | sed -e 's|,|\n|g' -e 's|\[||g' -e 's|\]||g')
  INCLUDE_TAGS_LIST=$(echo -e "${TAGS}" | grep -w "$2")
  INCLUDE_TAGS=$(echo ${INCLUDE_TAGS_LIST} | sed 's|\s|,|g')
  SKIP_TAGS_LIST=$(echo -e "${TAGS}" | grep -w "$3" )
  SKIP_TAGS=$(echo ${SKIP_TAGS_LIST} | sed 's|\s|,|g')
  $1 --tags "${INCLUDE_TAGS}" --skip-tags "${SKIP_TAGS}"
}

mkdir -p /opt/image-create
pushd /opt/image-create

  git clone https://github.com/openstack/openstack-ansible
  pushd openstack-ansible
    git checkout ${OSA_RELEASE}
    bash ./scripts/bootstrap-ansible.sh
  popd

  git clone https://github.com/openstack/openstack-ansible-${OSA_ROLE_NAME}
  pushd openstack-ansible-${OSA_ROLE_NAME}
    ansible-galaxy install --role-file=tests/ansible-role-requirements.yml
    sed 's| ansible_host=.*[0-9] | ansible_host=localhost |g' tests/inventory > ../artifact-inventory
    ln -s "$(pwd)" "/etc/ansible/roles/${OSA_ROLE_NAME}"
  popd

  ansible_tag_filter \
    "openstack-ansible -i artifact-inventory ${ELEMENT_DIR}/artifacts.yml -e upper_constraints=${OSA_CONSTRAINTS} -e role_name=${OSA_ROLE_NAME} -e dev_mode=${OSA_DEV_MODE}" \
    "install" \
    "config"
popd

